baseURL: 'https://pikemd.com/'
languageCode: en-us
title: EM Resources
theme: PaperMod
enableGitInfo: true
staticDir:
  - static

Copyright: © C. William Pike, MD

googleAnalytics: G-RJXBZM480J

params: 
  env: production 
  author: C. William Pike, MD
  ShowBreadCrumbs: true
  homeInfoParams:
    Title: Emergency Medicine Resources
    Content: Welcome to my Home Page for On shift resources, clinical teaching, and more

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary